import type { Metadata } from "next";
import "./globals.css";
import Providers from "@/components/providers";
import { poppins } from "./fonts";
import { Toaster } from "@/components/ui/sonner";
import Nav from "@/components/nav";

export const metadata: Metadata = {
  title: "Lumeo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.className} antialiased`}>
        <Providers>
          <Nav />
          {children}
          <Toaster />
        </Providers>
      </body>
    </html>
  );
}
